### ISSUE TITLE
this isn't much of a feature request...

### ISSUE THREAD

**Issue by LeonGamerPS4** [l1ttleO/ProjectFNF#44]
### What feature do you want to get added on the **base** engine?

Can you please update Psych Engine to 0.6.1/0.6.2?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TheKitBoi** [comment]
it's being worked on be patient

**Comment by LeonGamerPS4** [comment]
ok
