### ISSUE TITLE
Game crashes in freeplay

### ISSUE THREAD

**Issue by SuperSonic472** [l1ttleO/ProjectFNF#46]
### Describe your problem here.

I was working on InfOverZero Project (beta 2) and i saved the event for swapping the scroll (custom event) and when I went into freeplay the game crashed

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by l1ttleO** [comment]
Does the crash handler window appear? If so, please take a screenshot of it or send the crash report found in `crashes/` folder

If not, please specify what version of ProjectFNF you are using and edit your comment to mention if you changed source code and/or added Lua scripts

**Comment by SuperSonic472** [comment]
ok
[ProjectFNF_2022-08-05_02'11'47.txt](https://github.com/l1ttleO/ProjectFNF/files/9266241/ProjectFNF_2022-08-05_02.11.47.txt)
[ProjectFNF_2022-08-05_02'08'09.txt](https://github.com/l1ttleO/ProjectFNF/files/9266242/ProjectFNF_2022-08-05_02.08.09.txt)
these

**Comment by SuperSonic472** [comment]
one should be freeplay and the other story mode

**Comment by l1ttleO** [comment]
> ok [ProjectFNF_2022-08-05_02'11'47.txt](https://github.com/l1ttleO/ProjectFNF/files/9266241/ProjectFNF_2022-08-05_02.11.47.txt) [ProjectFNF_2022-08-05_02'08'09.txt](https://github.com/l1ttleO/ProjectFNF/files/9266242/ProjectFNF_2022-08-05_02.08.09.txt) these

You have a corrupted week file that doesn't have any songs in it. Paste this snippet in the JSON right after the opening bracket (`{`) to prevent the crash and then use the Week Editor to add songs

```json
"songs": [
		[
			"",
			"dad",
			[
				146,
				113,
				253
			]
		]
	],
```
