### ISSUE TITLE
Game crashes when setting animation frames to 8

### ISSUE THREAD

**Issue by SuperSonic472** [l1ttleO/ProjectFNF#51]
### Describe your problem here.

Whenever I try to set my character (Pantufa) to have 8 frames when i reload the animation the game just crashes
[ProjectFNF_2022-10-07_19'29'20.txt](https://github.com/l1ttleO/ProjectFNF/files/9737885/ProjectFNF_2022-10-07_19.29.20.txt)
[ProjectFNF_2022-10-07_19'32'05.txt](https://github.com/l1ttleO/ProjectFNF/files/9737886/ProjectFNF_2022-10-07_19.32.05.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by l1ttleO** [comment]
ProjectFNF does not touch the classes mentioned in the stacktraces, please report to Psych Engine
