### ISSUE TITLE
This repository should be merged with the east's one

### ISSUE THREAD

**Issue by Stilic** [l1ttleO/ProjectFNF#9]
Hello.
I am here for talk with @l1ttleO on some problems with this repository:
There is now two versions of PFNF: The one from this repository, and the [the east's version](https://github.com/ProjectFNF/ProjectFNF) (from me also). The l1ttleO's repo is maybe the most organized.
But, if we still maintain two "2.0" of the same engine on differents repositories, there is a big issue.
So, please, can you merge my and east's current work with yours on our repo, l1ttle0?

**Comment by l1ttleO** [comment]
1) no
2) and no
3) also no
4) did I forget to say no?
5) almost forgot to mention no
P.S. no
UPD. no
